### ISSUE TITLE
Enable bridging deposits for ERC-20 tokens

### ISSUE THREAD

**Issue by gndelia** [hemilabs/ui-monorepo#20]
- [x] Deposit ERC20 tokens #40 
- [x] Withdraw ERC20 tokens #41
- [ ] Prove ERC20 tokens See https://github.com/BVM-priv/ui-monorepo/issues/112
- [ ] Claim ERC20 tokens See https://github.com/BVM-priv/ui-monorepo/issues/113
