### ISSUE TITLE
Remove code from old claiming-capsule process

### ISSUE THREAD

**Issue by gndelia** [hemilabs/ui-monorepo#453]
After we dropped the process to claim capsules through the portal, there's code to remove.

## Frontend

- [x] Remove the [Recaptcha context](https://github.com/hemilabs/ui-monorepo/blob/main/webapp/components/recaptcha.tsx)
- [x] Remove the `next-recaptcha-v3` dependency
- [x] Remove the `NEXT_PUBLIC_CLAIM_TOKENS_URL` env variable from `.env` files
- [x] Remove welcome pack code (Done in https://github.com/hemilabs/ui-monorepo/pull/588)

## Backend

- [x] Remove the `claim-tokens` microservice code
- [x] Remove the lambdas from AWS
- [x] Drop the database in AWS
- [x] Optionally, drop the migrations code

## Misc

- [x] Close https://github.com/hemilabs/ui-monorepo/issues/267 as won't be implemented
- [x] Close https://github.com/hemilabs/ui-monorepo/issues/415 as won't be implemented
- [x] Close https://github.com/hemilabs/ui-monorepo/issues/183 as won't be implemented
- [x] Close https://github.com/hemilabs/ui-monorepo/issues/189 as won't be implemented
- [x] Update the Deployment process removing the deployment of the microservice
- [x] Remove the following secrets (From the workflow file and Github Secrets if defined there) 
  - [x] `RECAPTCHA_SECRET_KEY`
  - [x] `IP_QUALITY_SCORE_SECRET_KEY`
  - [x] `HASH_SECRET_KEY` (**ONLY** if we drop the database)
  - [x] `AWS_ACCESS_KEY_ID` (Unless it wants to be kept for any particular reason)
  - [x] `AWS_SECRET_ACCESS_KEY` (Unless it wants to be kept for any particular reason)
  - [x] All the `DEPLOY_POSTGRES_*` secrets (**ONLY** if we drop the database)
  - [x] `CLAIM_WELCOME_PACK_ZAPIER_WEBHOOK_URL`

~~TBC if we will implement this - blocked until that happens~~

**Comment by gndelia** [comment]
I've got green light to remove everything listed here, except the database (We will keep it a little bit more just in case)
